[target.xtensa-esp32s3-none-elf]
linker = "ldproxy"
runner = "espflash flash --partition-table partitions/esp32s3-n16r8.csv --monitor"
rustflags = [
  "-C",
  "link-arg=--ldproxy-linker",
  "-C",
  "link-arg=xtensa-esp32s3-elf-gcc",
  "-C",
  "link-arg=-Tlinkall.x",
  "-C",
  "link-arg=-nostartfiles",
]

[env]
ESP_LOG = "info"
