use crate::domain::{FigureKind, GameLine};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FigureCatalogEntry {
    pub index: u16,
    pub game_line: GameLine,
    pub kind: FigureKind,
    pub series: &'static str,
    pub name: &'static str,
    pub figure_number: u32,
}

macro_rules! entry {
    ($index:expr, $kind:ident, $series:expr, $name:expr, $figure_number:expr) => {
        FigureCatalogEntry {
            index: $index,
            game_line: GameLine::Infinity,
            kind: FigureKind::$kind,
            series: $series,
            name: $name,
            figure_number: $figure_number,
        }
    };
}

#[rustfmt::skip]
pub const INFINITY_CATALOG: &[FigureCatalogEntry] = &[
    entry!(0, Character, "The Incredibles", "Mr. Incredible", 0x0f4241),
    entry!(1, Character, "Monsters University", "Sulley", 0x0f4242),
    entry!(2, Character, "Pirates of the Caribbean", "Jack Sparrow", 0x0f4243),
    entry!(3, Character, "The Lone Ranger", "The Lone Ranger", 0x0f4244),
    entry!(4, Character, "The Lone Ranger", "Tonto", 0x0f4245),
    entry!(5, Character, "Cars", "Lightning McQueen", 0x0f4246),
    entry!(6, Character, "Cars", "Holley Shiftwell", 0x0f4247),
    entry!(7, Character, "Toy Story", "Buzz Lightyear", 0x0f4248),
    entry!(8, Character, "Toy Story", "Jessie", 0x0f4249),
    entry!(9, Character, "Monsters University", "Mike Wazowski", 0x0f424a),
    entry!(10, Character, "The Incredibles", "Mrs. Incredible", 0x0f424b),
    entry!(11, Character, "Pirates of the Caribbean", "Barbossa", 0x0f424c),
    entry!(12, Character, "Pirates of the Caribbean", "Davy Jones", 0x0f424d),
    entry!(13, Character, "Monsters University", "Randy", 0x0f424e),
    entry!(14, Character, "The Incredibles", "Syndrome", 0x0f424f),
    entry!(15, Character, "Toy Story", "Woody", 0x0f4250),
    entry!(16, Character, "Cars", "Mater", 0x0f4251),
    entry!(17, Character, "The Incredibles", "Dash", 0x0f4252),
    entry!(18, Character, "The Incredibles", "Violet", 0x0f4253),
    entry!(19, Character, "Cars", "Francesco Bernoulli", 0x0f4254),
    entry!(20, Character, "Fantasia", "Sorcerer's Apprentice Mickey", 0x0f4255),
    entry!(21, Character, "The Nightmare Before Christmas", "Jack Skellington", 0x0f4256),
    entry!(22, Character, "Tangled", "Rapunzel", 0x0f4257),
    entry!(23, Character, "Frozen", "Anna", 0x0f4258),
    entry!(24, Character, "Frozen", "Elsa", 0x0f4259),
    entry!(25, Character, "Phineas and Ferb", "Phineas Flynn", 0x0f425a),
    entry!(26, Character, "Phineas and Ferb", "Agent P", 0x0f425b),
    entry!(27, Character, "Wreck-It Ralph", "Wreck-It Ralph", 0x0f425c),
    entry!(28, Character, "Wreck-It Ralph", "Vanellope von Schweetz", 0x0f425d),
    entry!(29, Character, "The Incredibles", "Mr. Incredible (Crystal)", 0x0f425e),
    entry!(30, Character, "Pirates of the Caribbean", "Jack Sparrow (Crystal)", 0x0f425f),
    entry!(31, Character, "Monsters University", "Sulley (Crystal)", 0x0f4260),
    entry!(32, Character, "Cars", "Lightning McQueen (Crystal)", 0x0f4261),
    entry!(33, Character, "The Lone Ranger", "The Lone Ranger (Crystal)", 0x0f4262),
    entry!(34, Character, "Toy Story", "Buzz Lightyear (Crystal)", 0x0f4263),
    entry!(35, Character, "Phineas and Ferb", "Agent P (Crystal)", 0x0f4264),
    entry!(36, Character, "Fantasia", "Sorcerer's Apprentice Mickey (Crystal)", 0x0f4265),
    entry!(37, Character, "Toy Story", "Buzz Lightyear (Glowing)", 0x0f4266),
    entry!(38, LevelPiece, "Play Set", "The Incredibles - Pirates of the Caribbean - Monsters University Play Set", 0x1e8481),
    entry!(39, LevelPiece, "Play Set", "The Lone Ranger Play Set", 0x1e8482),
    entry!(40, LevelPiece, "Play Set", "Cars Play Set", 0x1e8483),
    entry!(41, LevelPiece, "Play Set", "Toy Story in Space Play Set", 0x1e8484),
    entry!(42, PowerDisc, "Power Disc", "Bolt - Bolt's Super Strength - Ability", 0x2dc6c3),
    entry!(43, PowerDisc, "Power Disc", "Wreck-It Ralph - Ralph's Power of Destruction - Ability", 0x2dc6c4),
    entry!(44, PowerDisc, "Power Disc", "Fantasia - Chernabog's Power - Ability", 0x2dc6c5),
    entry!(45, PowerDisc, "Power Disc", "Cars - C.H.R.O.M.E. Damage Increaser - Ability", 0x2dc6c6),
    entry!(46, PowerDisc, "Power Disc", "Phineas and Ferb - Dr. Doofenshmirtz's Damage-Inator! - Ability", 0x2dc6c7),
    entry!(47, PowerDisc, "Power Disc", "Frankenweenie - Electro-Charge - Ability", 0x2dc6c8),
    entry!(48, PowerDisc, "Power Disc", "Wreck-It Ralph - Fix-It Felix's Repair Power - Ability", 0x2dc6c9),
    entry!(49, PowerDisc, "Power Disc", "Tangled - Rapunzel's Healing - Ability", 0x2dc6ca),
    entry!(50, PowerDisc, "Power Disc", "Cars - C.H.R.O.M.E. Armor Shield - Ability", 0x2dc6cb),
    entry!(51, PowerDisc, "Power Disc", "Toy Story - Star Command Shield - Ability", 0x2dc6cc),
    entry!(52, PowerDisc, "Power Disc", "The Incredibles - Violet's Force Field - Ability", 0x2dc6cd),
    entry!(53, PowerDisc, "Power Disc", "Pirates of the Caribbean - Pieces of Eight - Ability", 0x2dc6ce),
    entry!(54, PowerDisc, "Power Disc", "DuckTales - Scrooge McDuck's Lucky Dime - Ability", 0x2dc6cf),
    entry!(55, PowerDisc, "Power Disc", "TRON - User Control Disc - Ability", 0x2dc6d0),
    entry!(56, PowerDisc, "Power Disc", "Fantasia - Mickey's Sorcerer Hat - Ability", 0x2dc6d1),
    entry!(57, PowerDisc, "Power Disc", "Toy Story - Emperor Zurg's Wrath - Ability", 0x2dc6fe),
    entry!(58, PowerDisc, "Power Disc", "The Sword in the Stone - Merlin's Summon - Ability", 0x2dc6ff),
    entry!(59, PowerDisc, "Power Disc", "Mickey Mouse Universe - Mickey's Car - Toy (Vehicle)", 0x3d0912),
    entry!(60, PowerDisc, "Power Disc", "Cinderella - Cinderella's Coach - Toy (Vehicle)", 0x3d0913),
    entry!(61, PowerDisc, "Power Disc", "The Muppets - Electric Mayhem Bus - Toy (Vehicle)", 0x3d0914),
    entry!(62, PowerDisc, "Power Disc", "101 Dalmatians - Cruella De Vil's Car - Toy (Vehicle)", 0x3d0915),
    entry!(63, PowerDisc, "Power Disc", "Toy Story - Pizza Planet Delivery Truck - Toy (Vehicle)", 0x3d0916),
    entry!(64, PowerDisc, "Power Disc", "Monsters, Inc. - Mike's New Car - Toy (Vehicle)", 0x3d0917),
    entry!(65, PowerDisc, "Power Disc", "Disney Parks - Disney Parks Parking Lot Tram - Toy (Vehicle)", 0x3d0919),
    entry!(66, PowerDisc, "Power Disc", "Peter Pan, Disney Parks - Jolly Roger - Toy (Aircraft)", 0x3d091a),
    entry!(67, PowerDisc, "Power Disc", "Dumbo, Disney Parks - Dumbo the Flying Elephant - Toy (Aircraft)", 0x3d091b),
    entry!(68, PowerDisc, "Power Disc", "Bolt - Calico Helicopter - Toy (Aircraft)", 0x3d091c),
    entry!(69, PowerDisc, "Power Disc", "Tangled - Maximus - Toy (Mount)", 0x3d091d),
    entry!(70, PowerDisc, "Power Disc", "Brave - Angus - Toy (Mount)", 0x3d091e),
    entry!(71, PowerDisc, "Power Disc", "Aladdin - Abu the Elephant - Toy (Mount)", 0x3d091f),
    entry!(72, PowerDisc, "Power Disc", "The Adventures of Ichabod and Mr. Toad - Headless Horseman's Horse - Toy (Mount)", 0x3d0920),
    entry!(73, PowerDisc, "Power Disc", "Beauty and the Beast - Phillipe - Toy (Mount)", 0x3d0921),
    entry!(74, PowerDisc, "Power Disc", "Mulan - Khan - Toy (Mount)", 0x3d0922),
    entry!(75, PowerDisc, "Power Disc", "Tarzan - Tantor - Toy (Mount)", 0x3d0923),
    entry!(76, PowerDisc, "Power Disc", "Mulan - Dragon Firework Cannon - Toy (Weapon)", 0x3d0924),
    entry!(77, PowerDisc, "Power Disc", "Lilo & Stitch - Stitch's Blaster - Toy (Weapon)", 0x3d0925),
    entry!(78, PowerDisc, "Power Disc", "Toy Story, Disney Parks - Toy Story Mania Blaster - Toy (Weapon)", 0x3d0926),
    entry!(79, PowerDisc, "Power Disc", "Alice in Wonderland - Flamingo Croquet Mallet - Toy (Weapon)", 0x3d0927),
    entry!(80, PowerDisc, "Power Disc", "Up - Carl Fredricksen's Cane - Toy (Weapon)", 0x3d0928),
    entry!(81, PowerDisc, "Power Disc", "Lilo & Stitch - Hangin' Ten Stitch With Surfboard - Toy (Hoverboard)", 0x3d0929),
    entry!(82, PowerDisc, "Power Disc", "Condorman - Condorman Glider - Toy (Glider)", 0x3d092a),
    entry!(83, PowerDisc, "Power Disc", "WALL-E - WALL-E's Fire Extinguisher - Toy (Jetpack)", 0x3d092b),
    entry!(84, PowerDisc, "Power Disc", "TRON - On the Grid - Customization (Terrain)", 0x3d092c),
    entry!(85, PowerDisc, "Power Disc", "WALL-E - WALL-E's Collection - Customization (Terrain)", 0x3d092d),
    entry!(86, PowerDisc, "Power Disc", "Wreck-It Ralph - King Candy's Dessert Toppings - Customization (Terrain)", 0x3d092e),
    entry!(87, PowerDisc, "Power Disc", "Frankenweenie - Victor's Experiments - Customization (Terrain)", 0x3d0930),
    entry!(88, PowerDisc, "Power Disc", "The Nightmare Before Christmas - Jack's Scary Decorations - Customization (Terrain)", 0x3d0931),
    entry!(89, PowerDisc, "Power Disc", "Frozen - Frozen Flourish - Customization (Terrain)", 0x3d0933),
    entry!(90, PowerDisc, "Power Disc", "Tangled - Rapunzel's Kingdom - Customization (Terrain)", 0x3d0934),
    entry!(91, PowerDisc, "Power Disc", "TRON - TRON Interface - Customization (Skydome)", 0x3d0935),
    entry!(92, PowerDisc, "Power Disc", "WALL-E - Buy N Large Atmosphere - Customization (Skydome)", 0x3d0936),
    entry!(93, PowerDisc, "Power Disc", "Wreck-It Ralph - Sugar Rush Sky - Customization (Skydome)", 0x3d0937),
    entry!(94, PowerDisc, "Power Disc", "The Nightmare Before Christmas - Halloween Town Sky - Customization (Skydome)", 0x3d093a),
    entry!(95, PowerDisc, "Power Disc", "Frozen - Chill in the Air - Customization (Skydome)", 0x3d093c),
    entry!(96, PowerDisc, "Power Disc", "Tangled - Rapunzel's Birthday Sky - Customization (Skydome)", 0x3d093d),
    entry!(97, PowerDisc, "Power Disc", "Toy Story, Disney Parks - Astro Blasters Space Cruiser - Toy (Vehicle)", 0x3d0940),
    entry!(98, PowerDisc, "Power Disc", "Finding Nemo - Marlin's Reef - Customization (Terrain)", 0x3d0941),
    entry!(99, PowerDisc, "Power Disc", "Finding Nemo - Nemo's Seascape - Customization (Skydome)", 0x3d0942),
    entry!(100, PowerDisc, "Power Disc", "Alice in Wonderland - Alice's Wonderland - Customization (Terrain)", 0x3d0943),
    entry!(101, PowerDisc, "Power Disc", "Alice in Wonderland - Tulgey Wood - Customization (Skydome)", 0x3d0944),
    entry!(102, PowerDisc, "Power Disc", "Phineas and Ferb - Tri-State Area Terrain", 0x3d0945),
    entry!(103, PowerDisc, "Power Disc", "Phineas and Ferb - Danville Sky", 0x3d0946),
    entry!(104, Character, "Aladdin", "Aladdin", 0x0f42b5),
    entry!(105, Character, "Aladdin", "Jasmine", 0x0f42c1),
    entry!(106, Character, "Big Hero 6", "Baymax", 0x0f42bb),
    entry!(107, Character, "Big Hero 6", "Hiro Hamada", 0x0f42ba),
    entry!(108, Character, "Brave", "Merida", 0x0f42b7),
    entry!(109, Character, "Duck Universe", "Donald Duck", 0x0f42b4),
    entry!(110, Character, "Guardians of the Galaxy", "Drax the Destroyer", 0x0f42af),
    entry!(111, Character, "Guardians of the Galaxy", "Gamora", 0x0f42b0),
    entry!(112, Character, "Guardians of the Galaxy", "Groot", 0x0f42a8),
    entry!(113, Character, "Guardians of the Galaxy", "Rocket Raccoon", 0x0f42a9),
    entry!(114, Character, "Guardians of the Galaxy", "Ronan the Accuser", 0x0f42bd),
    entry!(115, Character, "Guardians of the Galaxy", "Star-Lord", 0x0f42aa),
    entry!(116, Character, "Guardians of the Galaxy", "Yondu", 0x0f42c0),
    entry!(117, Character, "Lilo & Stitch", "Stitch", 0x0f42b6),
    entry!(118, Character, "Maleficent", "Maleficent", 0x0f42b9),
    entry!(119, Character, "The Avengers", "Black Widow", 0x0f42ad),
    entry!(120, Character, "The Avengers", "Captain America", 0x0f42a4),
    entry!(121, Character, "The Avengers", "Falcon", 0x0f42bf),
    entry!(122, Character, "The Avengers", "Hawkeye", 0x0f42ae),
    entry!(123, Character, "The Avengers", "Hulk", 0x0f42a5),
    entry!(124, Character, "The Avengers", "Iron Man", 0x0f42a6),
    entry!(125, Character, "The Avengers", "Loki", 0x0f42bc),
    entry!(126, Character, "The Avengers", "Thor", 0x0f42a7),
    entry!(127, Character, "Tinker Bell", "Tinker Bell", 0x0f42b8),
    entry!(128, Character, "Ultimate Spider-Man", "Black Suit Spider-Man", 0x0f42c6),
    entry!(129, Character, "Ultimate Spider-Man", "Green Goblin", 0x0f42be),
    entry!(130, Character, "Ultimate Spider-Man", "Iron Fist", 0x0f42b1),
    entry!(131, Character, "Ultimate Spider-Man", "Nick Fury", 0x0f42ac),
    entry!(132, Character, "Ultimate Spider-Man", "Nova", 0x0f42b2),
    entry!(133, Character, "Ultimate Spider-Man", "Spider-Man", 0x0f42ab),
    entry!(134, Character, "Ultimate Spider-Man", "Venom", 0x0f42b3),
    entry!(135, LevelPiece, "Play Set", "Marvel's Guardians of the Galaxy Play Set", 0x1e84e6),
    entry!(136, LevelPiece, "Play Set", "Marvel's Spider-Man Play Set (included in PS Vita starter pack)", 0x1e84e5),
    entry!(137, LevelPiece, "Play Set", "Marvel's The Avengers Play Set (included in starter pack)", 0x1e84e4),
    entry!(138, PowerDisc, "2.0 Power Disc", "Devil Dinosaur, Marvel Comics - Dinosaur World - Customization (Terrain)", 0x3d096e),
    entry!(139, PowerDisc, "2.0 Power Disc", "Devil Dinosaur, Marvel Comics - Forgotten Skies - Customization (Skydome)", 0x3d097e),
    entry!(140, PowerDisc, "2.0 Power Disc", "Ghost Rider, Marvel Comics - Ghost Rider's Chain Whip - Toy (Weapon)", 0x3d099c),
    entry!(141, PowerDisc, "2.0 Power Disc", "Marvel Comics - Ant-Man - Ability (Team Up)", 0x2dc772),
    entry!(142, PowerDisc, "2.0 Power Disc", "Marvel Comics - Cloak of Levitation - Toy (Glider)", 0x3d09a4),
    entry!(143, PowerDisc, "2.0 Power Disc", "Marvel Comics - Gamma Rays - Ability (Costume)", 0x2dc777),
    entry!(144, PowerDisc, "2.0 Power Disc", "Marvel Comics - Sorcerer Supreme - Ability (Event)", 0x2dc76d),
    entry!(145, PowerDisc, "2.0 Power Disc", "Marvel Comics - World War Hulk - Customization (Terrain)", 0x3d0967),
    entry!(146, PowerDisc, "2.0 Power Disc", "Marvel Comics - World War Hulk Sky - Customization (Skydome)", 0x3d0977),
    entry!(147, PowerDisc, "2.0 Power Disc", "Marvel's Guardians of the Galaxy, Marvel Comics - Groot's Roots - Customization (Terrain)", 0x3d096f),
    entry!(148, PowerDisc, "2.0 Power Disc", "Marvel's Guardians of the Galaxy, Marvel Comics - Groot's View - Customization (Skydome)", 0x3d097f),
    entry!(149, PowerDisc, "2.0 Power Disc", "Marvel's Guardians of the Galaxy, Marvel Comics - Space Armor - Ability (Costume)", 0x2dc77f),
    entry!(150, PowerDisc, "2.0 Power Disc", "Marvel's Guardians of the Galaxy, Marvel Comics - Star-Lord's Galaxy - Customization (Terrain)", 0x3d096d),
    entry!(151, PowerDisc, "2.0 Power Disc", "Marvel's Guardians of the Galaxy, Marvel Comics - The Rip - Customization (Skydome)", 0x3d097d),
    entry!(152, PowerDisc, "2.0 Power Disc", "Marvel's Guardians of the Galaxy, Marvel Comics - Yondu - Ability (Team Up)", 0x2dc774),
    entry!(153, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Black Panther's Vibranium Knives - Toy (Weapon)", 0x3d09a3),
    entry!(154, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Falcon's Wings - Toy (Glider)", 0x3d09a0),
    entry!(155, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Hydra Motorcycle - Toy (Motorcycle)", 0x3d098c),
    entry!(156, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Infinity Gauntlet - Ability (Event)", 0x2dc76b),
    entry!(157, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Iron Patriot - Ability (Team Up)", 0x2dc771),
    entry!(158, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Lola - Toy (Vehicle)", 0x3d09c1),
    entry!(159, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Odin's Horse - Toy (Mount)", 0x3d0997),
    entry!(160, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - S.H.I.E.L.D. Containment Truck - Toy (Vehicle)", 0x3d0985),
    entry!(161, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - S.H.I.E.L.D. Hellicarrier Strike - Ability (Event)", 0x2dc768),
    entry!(162, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Sentinel of Liberty - Ability (Costume)", 0x2dc77d),
    entry!(163, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Stark Arc Reactor - Ability (Costume)", 0x2dc776),
    entry!(164, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Stark Tech - Customization (Terrain)", 0x3d0965),
    entry!(165, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - The Avenjet - Toy (Aircraft)", 0x3d09c3),
    entry!(166, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - View from the Suit - Customization (Skydome)", 0x3d0975),
    entry!(167, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Winter Soldier - Ability (Team Up)", 0x2dc775),
    entry!(168, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Alien Symbiote - Ability (Costume)", 0x2dc778),
    entry!(169, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Jack-O-Lantern's Glider - Toy (Glider)", 0x3d0993),
    entry!(170, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Spider Sky - Customization (Skydome)", 0x3d0976),
    entry!(171, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Spider-Buggy - Toy (Vehicle)", 0x3d0994),
    entry!(172, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Spider-Copter - Toy (Aircraft)", 0x3d0991),
    entry!(173, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Spider-Cycle - Toy (Motorcycle)", 0x3d09c2),
    entry!(174, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Spider-Glider - Toy (Glider)", 0x3d09c4),
    entry!(175, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - Spidey's Streets - Customization (Terrain)", 0x3d0966),
    entry!(176, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - The Immortal Iron Fist - Ability (Costume)", 0x2dc77e),
    entry!(177, PowerDisc, "2.0 Power Disc", "Spider-Man Comics, Marvel Comics - White Tiger - Ability (Team Up)", 0x2dc773),
    entry!(178, PowerDisc, "2.0 Power Disc", "Aladdin - Aladdin's Magic Carpet - Toy (Aircraft)", 0x3d09a5),
    entry!(179, PowerDisc, "2.0 Power Disc", "Aladdin - Rags To Riches - Ability (Costume)", 0x2dc780),
    entry!(180, PowerDisc, "2.0 Power Disc", "Alice in Wonderland, Disney Parks - Alice in Wonderland's Caterpillar - Toy (Vehicle)", 0x3d0989),
    entry!(181, PowerDisc, "2.0 Power Disc", "Bedknobs and Broomsticks - Eglantine's Motorcycle - Toy (Vehicle)", 0x3d098a),
    entry!(182, PowerDisc, "2.0 Power Disc", "Big Hero 6 - Honey Lemon's Ice Capsules - Toy (Weapon)", 0x3d09a6),
    entry!(183, PowerDisc, "2.0 Power Disc", "Disney Parks - A Small World - Customization (Terrain)", 0x3d0974),
    entry!(184, PowerDisc, "2.0 Power Disc", "Disney Parks - Fantasyland Carousel Horse - Toy (Vehicle)", 0x3d0996),
    entry!(185, PowerDisc, "2.0 Power Disc", "Disney Parks - Main Street Electrical Parade Float - Toy (Vehicle)", 0x3d0986),
    entry!(186, PowerDisc, "2.0 Power Disc", "Disney Parks - Skies of the World - Customization (Skydome)", 0x3d0984),
    entry!(187, PowerDisc, "2.0 Power Disc", "Disney's Darkwing Duck - Darkwing Duck's Grappling Gun - Toy (Weapon)", 0x3d099a),
    entry!(188, PowerDisc, "2.0 Power Disc", "Disney's Darkwing Duck - Darkwing Duck's Ratcatcher - Toy (Vehicle)", 0x3d098d),
    entry!(189, PowerDisc, "2.0 Power Disc", "Fantasia - Chernabog's Spirit Cyclone - Ability (Event)", 0x2dc76f),
    entry!(190, PowerDisc, "2.0 Power Disc", "Gravity Falls - Gravity Falls Forest - Customization (Terrain)", 0x3d0968),
    entry!(191, PowerDisc, "2.0 Power Disc", "Gravity Falls - Gravity Falls Sky - Customization (Skydome)", 0x3d0978),
    entry!(192, PowerDisc, "2.0 Power Disc", "Gravity Falls - Mabel's Kittens for Fists - Toy (Weapon)", 0x3d09a1),
    entry!(193, PowerDisc, "2.0 Power Disc", "Gus - Gus the Mule - Toy (Mount)", 0x3d0998),
    entry!(194, PowerDisc, "2.0 Power Disc", "Hercules - Zeus' Thunderbolt - Ability (Event)", 0x2dc769),
    entry!(195, PowerDisc, "2.0 Power Disc", "Mickey, Donald, and Goofy The Three Musketeers - All For One - Ability (Costume)", 0x2dc779),
    entry!(196, PowerDisc, "2.0 Power Disc", "Mulan - Mulan's Countryside - Customization (Terrain)", 0x3d0970),
    entry!(197, PowerDisc, "2.0 Power Disc", "Mulan - The Middle Kingdom - Customization (Skydome)", 0x3d0980),
    entry!(198, PowerDisc, "2.0 Power Disc", "Peter Pan - Neverland - Customization (Terrain)", 0x3d0969),
    entry!(199, PowerDisc, "2.0 Power Disc", "Peter Pan - Second Star to the Right - Customization (Skydome)", 0x3d0979),
    entry!(200, PowerDisc, "2.0 Power Disc", "Phineas and Ferb - Aerial Area Rug - Toy (Aircraft)", 0x3d0992),
    entry!(201, PowerDisc, "2.0 Power Disc", "Pirates of the Caribbean - Cursed Pirate Gold - Ability (Costume)", 0x2dc77c),
    entry!(202, PowerDisc, "2.0 Power Disc", "Sleeping Beauty - Maleficent's Spell Cast - Ability (Event)", 0x2dc76e),
    entry!(203, PowerDisc, "2.0 Power Disc", "The Adventures of Ichabod and Mr. Toad, Disney Parks - Mr Toad's Motorcar - Toy (Vehicle)", 0x3d0987),
    entry!(204, PowerDisc, "2.0 Power Disc", "The Incredibles - Glory Days - Ability (Costume)", 0x2dc77b),
    entry!(205, PowerDisc, "2.0 Power Disc", "The Jungle Book - King Louie's Monkeys - Ability (Event)", 0x2dc76a),
    entry!(206, PowerDisc, "2.0 Power Disc", "The Lion King - Simba's Pridelands - Customization (Terrain)", 0x3d096a),
    entry!(207, PowerDisc, "2.0 Power Disc", "The Lion King - The King's Domain - Customization (Skydome)", 0x3d097a),
    entry!(208, PowerDisc, "2.0 Power Disc", "The Muppets - Le Maximum - Toy (Vehicle)", 0x3d0988),
    entry!(209, PowerDisc, "2.0 Power Disc", "The Muppets - Lew Zealand's Boomerang Fish - Toy (Weapon)", 0x3d099d),
    entry!(210, PowerDisc, "2.0 Power Disc", "The Muppets - USS Swinetrek - Toy (Aircraft)", 0x3d098f),
    entry!(211, PowerDisc, "2.0 Power Disc", "The Nightmare Before Christmas - Jack Skellington's Reindeer - Toy (Mount)", 0x3d0995),
    entry!(212, PowerDisc, "2.0 Power Disc", "The Nightmare Before Christmas - Sandy Claws Surprise - Ability (Costume)", 0x2dc77a),
    entry!(213, PowerDisc, "2.0 Power Disc", "The Rescuers - Medusa's Swamp Mobile - Toy (Vehicle)", 0x3d098b),
    entry!(214, PowerDisc, "2.0 Power Disc", "Treasure Planet - Jim Hawkins' Solar Board - Toy (Hoverboard)", 0x3d09a2),
    entry!(215, PowerDisc, "2.0 Power Disc", "Wreck-It Ralph - Calhoun's Command - Customization (Terrain)", 0x3d096c),
    entry!(216, PowerDisc, "2.0 Power Disc", "Wreck-It Ralph - CyBug Swarm - Customization (Skydome)", 0x3d097c),
    entry!(217, PowerDisc, "2.0 Power Disc", "Wreck-It-Ralph - Sergeant Calhoun's Blaster - Toy (Weapon)", 0x3d099e),
    entry!(218, PowerDisc, "2.0 Power Disc", "Aladdin - Jasmine's Palace View - Customization (Skydome)", 0x3d09a7),
    entry!(219, PowerDisc, "2.0 Power Disc", "Aladdin - The Sands of Agrabah - Customization (Terrain)", 0x3d0971),
    entry!(220, PowerDisc, "2.0 Power Disc", "Marvel Comics - Capt. Marvel - Ability (Team Up)", 0x2dc770),
    entry!(221, PowerDisc, "2.0 Power Disc", "Marvel's The Avengers, Marvel Comics - Ultimate Falcon - Ability (Costume)", 0x2dc781),
    entry!(222, PowerDisc, "2.0 Power Disc", "TRON - Light Cycle - Toy (Vehicle)", 0x3d09c5),
    entry!(223, PowerDisc, "2.0 Power Disc", "TRON - Light Jet - Toy (Aircraft)", 0x3d09c6),
    entry!(224, LevelPiece, "Toy Box Game", "Brave - Brave Forest Siege", 0x1e84ea),
    entry!(225, LevelPiece, "Toy Box Game", "Guardians of the Galaxy - Escape from the Kyln", 0x1e84e8),
    entry!(226, LevelPiece, "Toy Box Game", "Lilo & Stitch - Stitch's Tropical Rescue", 0x1e84e9),
    entry!(227, LevelPiece, "Toy Box Game", "Marvel's The Avengers - Assault on Asgard", 0x1e84e7),
    entry!(228, Character, "Alice Through the Looking Glass", "Alice Kingsleigh", 0x0f436f),
    entry!(229, Character, "Alice Through the Looking Glass", "Mad Hatter", 0x0f4370),
    entry!(230, Character, "Alice Through the Looking Glass", "Time", 0x0f4371),
    entry!(231, Character, "Avengers Age of Ultron", "Hulkbuster Iron Man", 0x0f432e),
    entry!(232, Character, "Avengers Age of Ultron", "Ultron", 0x0f4322),
    entry!(233, Character, "Captain America Civil War", "Ant-Man", 0x0f4323),
    entry!(234, Character, "Captain America Civil War", "Black Panther", 0x0f4336),
    entry!(235, Character, "Captain America Civil War", "Captain America - The First Avenger", 0x0f4325),
    entry!(236, Character, "Captain America Civil War", "Vision", 0x0f4321),
    entry!(237, Character, "Finding Dory", "Dory", 0x0f436d),
    entry!(238, Character, "Finding Dory", "Nemo", 0x0f436c),
    entry!(239, Character, "Frozen", "Olaf", 0x0f4320),
    entry!(240, Character, "Inside Out", "Anger", 0x0f4319),
    entry!(241, Character, "Inside Out", "Disgust", 0x0f431c),
    entry!(242, Character, "Inside Out", "Fear", 0x0f431a),
    entry!(243, Character, "Inside Out", "Joy", 0x0f4318),
    entry!(244, Character, "Inside Out", "Sadness", 0x0f431b),
    entry!(245, Character, "Mouse Universe", "Mickey Mouse", 0x0f431d),
    entry!(246, Character, "Mouse Universe", "Minnie Mouse", 0x0f431e),
    entry!(247, Character, "Mulan", "Mulan", 0x0f431f),
    entry!(248, Character, "Peter Pan", "Peter Pan", 0x0f4372),
    entry!(249, Character, "Star Wars", "Boba Fett", 0x0f4313),
    entry!(250, Character, "Star Wars", "Chewbacca", 0x0f4311),
    entry!(251, Character, "Star Wars", "Darth Maul", 0x0f430c),
    entry!(252, Character, "Star Wars", "Darth Vader (Light FX)", 0x0f4333),
    entry!(253, Character, "Star Wars", "Darth Vader", 0x0f4312),
    entry!(254, Character, "Star Wars", "Han Solo", 0x0f430f),
    entry!(255, Character, "Star Wars", "Leia Organa", 0x0f4310),
    entry!(256, Character, "Star Wars", "Luke Skywalker (Light FX)", 0x0f4332),
    entry!(257, Character, "Star Wars", "Luke Skywalker", 0x0f430e),
    entry!(258, Character, "Star Wars Rebels", "Ezra Bridger", 0x0f4314),
    entry!(259, Character, "Star Wars Rebels", "Kanan Jarrus (Light FX)", 0x0f4334),
    entry!(260, Character, "Star Wars Rebels", "Kanan Jarrus", 0x0f4315),
    entry!(261, Character, "Star Wars Rebels", "Sabine Wren", 0x0f4316),
    entry!(262, Character, "Star Wars Rebels", "Zeb Orrelios", 0x0f4317),
    entry!(263, Character, "Star Wars The Clone Wars", "Ahsoka Tano", 0x0f430b),
    entry!(264, Character, "Star Wars The Clone Wars", "Anakin Skywalker (Light FX)", 0x0f432f),
    entry!(265, Character, "Star Wars The Clone Wars", "Anakin Skywalker", 0x0f4308),
    entry!(266, Character, "Star Wars The Clone Wars", "Obi-Wan Kenobi (Light FX)", 0x0f4330),
    entry!(267, Character, "Star Wars The Clone Wars", "Obi-Wan Kenobi", 0x0f4309),
    entry!(268, Character, "Star Wars The Clone Wars", "Yoda (Light FX)", 0x0f4331),
    entry!(269, Character, "Star Wars The Clone Wars", "Yoda", 0x0f430a),
    entry!(270, Character, "Star Wars The Force Awakens", "Finn", 0x0f4326),
    entry!(271, Character, "Star Wars The Force Awakens", "Kylo Ren (Light FX)", 0x0f4335),
    entry!(272, Character, "Star Wars The Force Awakens", "Kylo Ren", 0x0f4327),
    entry!(273, Character, "Star Wars The Force Awakens", "Poe Dameron", 0x0f4328),
    entry!(274, Character, "Star Wars The Force Awakens", "Rey", 0x0f4329),
    entry!(275, Character, "The Good Dinosaur", "Spot", 0x0f432b),
    entry!(276, Character, "The Jungle Book", "Baloo", 0x0f436e),
    entry!(277, Character, "Tron Legacy", "Quorra", 0x0f42d7),
    entry!(278, Character, "Tron Legacy", "Sam Flynn", 0x0f42d6),
    entry!(279, Character, "Zootopia", "Judy Hopps", 0x0f432d),
    entry!(280, Character, "Zootopia", "Nick Wilde", 0x0f432c),
    entry!(281, LevelPiece, "Play Set", "Finding Dory Play Set", 0x1e85ac),
    entry!(282, LevelPiece, "Play Set", "Inside Out Play Set", 0x1e8548),
    entry!(283, LevelPiece, "Play Set", "Marvel Battlegrounds Play Set", 0x1e854d),
    entry!(284, LevelPiece, "Play Set", "Star Wars Rise Against the Empire Play Set", 0x1e854b),
    entry!(285, LevelPiece, "Play Set", "Star Wars The Force Awakens Play Set", 0x1e854c),
    entry!(286, LevelPiece, "Play Set", "Star Wars Twilight of the Republic Play Set (included in starter pack)", 0x1e854a),
    entry!(287, PowerDisc, "3.0 Power Disc", "Star Wars - Forest of Felucia - Customization (Terrain)", 0x3d09cd),
    entry!(288, PowerDisc, "3.0 Power Disc", "Star Wars - Galactic Team-Up Mace Windu - Ability (Team-Up)", 0x2dc78e),
    entry!(289, PowerDisc, "3.0 Power Disc", "Star Wars - General Grievous' Wheel Bike - Toy (Vehicle)", 0x3d09cf),
    entry!(290, PowerDisc, "3.0 Power Disc", "Star Wars - Princess Leia Boushh Disguise - Ability (Costume Change)", 0x2dc7a4),
    entry!(291, PowerDisc, "3.0 Power Disc", "Star Wars - Rebel Alliance Flight Suit - Ability (Costume Change)", 0x2dc791),
    entry!(292, PowerDisc, "3.0 Power Disc", "Star Wars - Skies over Felucia - Customization (Skydome)", 0x3d09cc),
    entry!(293, PowerDisc, "3.0 Power Disc", "Star Wars - Slave I - Toy (Aircraft)", 0x3d09d2),
    entry!(294, PowerDisc, "3.0 Power Disc", "Star Wars - Y-Wing Starfighter - Toy (Aircraft)", 0x3d09d3),
    entry!(295, PowerDisc, "3.0 Power Disc", "Tomorrowland - Retro Ray Gun - Toy (Weapon)", 0x3d09c9),
    entry!(296, PowerDisc, "3.0 Power Disc", "Tomorrowland - Tomorrowland Futurescape - Customization (Terrain)", 0x3d09ca),
    entry!(297, PowerDisc, "3.0 Power Disc", "Tomorrowland - Tomorrowland Stratosphere - Customization (Skydome)", 0x3d09cb),
    entry!(298, PowerDisc, "3.0 Power Disc", "Tomorrowland - Tomorrowland Time Bomb - Ability (Event)", 0x2dc788),
    entry!(299, PowerDisc, "3.0 Power Disc", "Kingdom Hearts - King Mickey - Ability (Costume Change)", 0x2dc7a7),
    entry!(300, PowerDisc, "3.0 Power Disc", "Marvel Comics - Cosmic Cube Blast - Ability (Event)", 0x2dc7a3),
    entry!(301, PowerDisc, "3.0 Power Disc", "Marvel Comics - Darkhawk's Blast - Ability (Event)", 0x2dc7a2),
    entry!(302, PowerDisc, "3.0 Power Disc", "Marvel Comics - Ghost Rider's Motorcycle - Toy (Vehicle)", 0x3d09e0),
    entry!(303, PowerDisc, "3.0 Power Disc", "Marvel Comics - Nova Corps Strike - Ability (Event)", 0x2dc7a6),
    entry!(304, PowerDisc, "3.0 Power Disc", "Star Wars - Finn's Stormtrooper Costume - Ability (Costume Change)", 0x2dc798),
    entry!(305, PowerDisc, "3.0 Power Disc", "Star Wars - Poe's Resistance Jacket - Ability (Costume Change)", 0x2dc799),
    entry!(306, PowerDisc, "3.0 Power Disc", "Star Wars - Quad Jumper - Toy (Aircraft)", 0x3d09e5),
    entry!(307, PowerDisc, "3.0 Power Disc", "Star Wars - Resistance Tactical Strike - Ability (Event)", 0x2dc79a),
    entry!(308, PowerDisc, "3.0 Power Disc", "The Good Dinosaur - Arlo - Toy (Mount)", 0x3d09d4),
    entry!(309, PowerDisc, "3.0 Power Disc", "The Good Dinosaur - Butch - Toy (Mount)", 0x3d09d6),
    entry!(310, PowerDisc, "3.0 Power Disc", "The Good Dinosaur - Nash - Toy (Mount)", 0x3d09d5),
    entry!(311, PowerDisc, "3.0 Power Disc", "The Good Dinosaur - Ramsey - Toy (Mount)", 0x3d09d7),
    entry!(312, PowerDisc, "3.0 Power Disc", "Zootopia - Meter Maid Judy - Ability (Costume Change)", 0x2dc79f),
    entry!(313, PowerDisc, "3.0 Power Disc", "Zootopia - Officer Wilde - Ability (Costume Change)", 0x2dc79e),
    entry!(314, PowerDisc, "3.0 Power Disc", "Zootopia - Sahara Square Sands - Customization (Terrain)", 0x3d09dd),
    entry!(315, PowerDisc, "3.0 Power Disc", "Zootopia - Stars Over Sahara Square - Customization (Skydome)", 0x3d09dc),
    entry!(316, LevelPiece, "Toy Box Game", "Toy Box Speedway", 0x1e854e),
    entry!(317, LevelPiece, "Toy Box Game", "Toy Box Takeover", 0x1e854f),
];

pub fn infinity_catalog_entry(index: u16) -> Option<&'static FigureCatalogEntry> {
    INFINITY_CATALOG.get(index as usize)
}

pub fn find_infinity_catalog_entry(figure_number: u32) -> Option<&'static FigureCatalogEntry> {
    INFINITY_CATALOG
        .iter()
        .find(|entry| entry.figure_number == figure_number)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_expected_infinity_1_entries() {
        assert_eq!(INFINITY_CATALOG.len(), 318);
        assert_eq!(INFINITY_CATALOG[0].figure_number, 0x0f4241);
        assert_eq!(INFINITY_CATALOG[0].name, "Mr. Incredible");
        assert_eq!(INFINITY_CATALOG[38].kind, FigureKind::LevelPiece);
        assert_eq!(INFINITY_CATALOG[51].figure_number, 0x2dc6cc);
        assert_eq!(
            find_infinity_catalog_entry(0x0f42a6).map(|entry| entry.name),
            Some("Iron Man")
        );
        assert_eq!(
            find_infinity_catalog_entry(0x0f4308).map(|entry| entry.name),
            Some("Anakin Skywalker")
        );
        assert_eq!(INFINITY_CATALOG[316].kind, FigureKind::LevelPiece);
        assert_eq!(INFINITY_CATALOG[317].figure_number, 0x1e854f);
    }
}
